### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by hsellik** [microsoft/near-duplicate-code-detector#2]
For anyone trying this tool out and encountering similar issue. 

**Problem:**
While testing on a very small scale, I encounterent `ArgumentOutOfRangeException` in `CloneGorups.cs:line 47`.

**Cause:**
If there are very 2 entries in `duplicationFactors` variable, meaning there are only 2 unique clone clusters, then the `midpoint` becomes 1. Then the `duplicationFactors[midpoint + 1]` is causing an index out of range exception.

**Solution:**
Use on bigger projects and assume that the `duplicationFactors` includes more entries or add a special case to the code where duplicationFactors.Count == 2.

**Error log:**
```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NearCloneDetector.CloneGroups..ctor(IEnumerable`1 clonePairs) in /near-duplicate-code-detector/DuplicateCodeDetector/CloneGroups.cs:line 47
   at NearCloneDetector.CloneDetectorCli.DetectClones(IDictionary`2 arguments) in /near-duplicate-code-detector/DuplicateCodeDetector/CloneDetectorCli.cs:line 68
   at NearCloneDetector.CloneDetectorCli.Main(String[] args) in /near-duplicate-code-detector/DuplicateCodeDetector/CloneDetectorCli.cs:line 30
```

**Comment by mallamanis** [comment]
Hi @hsellik,
Thanks for reporting this!

@mdrafiqulrabin provided a solution, which I just merged. Hope this works for you. Feel free to reopen the issue if this isn't resolved. And of course, feel free to submit new issues if you bump into any problems!
